### ISSUE TITLE
TODO for version 3.0.0 - Complete Overhaul!

### ISSUE THREAD

**Issue by bluecaret** [bluecaret/carettab#76]
I am working on rewriting CaretTab from scratch to enable better performance, speed, and opportunities for more advanced features! This is large work that is going to take a while, I currently make this extension as a hobby in my free time, but no worries, the next update will happen!

To keep myself on track as well as let you all know what is coming down the pipeline and know how far along it is, this issue will track the progress of the 3.0.0 update. 

More items are likely to be added to this list as I think of them, but this is what is planned so far. Keep in mind the list includes a lot of items that are already in the extension, this is because I am scratching what I did before and starting over so I have to recreate what I already had in place.

General TODO
- [x] Investigate different frameworks to use and try proof-of-concepts. (decided on Angular)
- [x] Create basic extension in Angular 6
- [x] Setup better workflow NPM for easy development and contributions
- [x] Setup a storage service for easier saving/retrieving of data
- [ ] Setup a build process for cross-browser support
- [ ] Investigate support of Microsoft Edge
- [ ] Investigate support of Opera
- [x] Design full screen settings UI with page preview
- [ ] Investigate use of Angular Material design framework
- [x] Custom sizing options per element proof-of-concept (each element can be sized independently, as well as globally)
- [x] More robust data structure to enable unlimited number of items (quick links, clocks, etc.)
- [ ] Create splash screen for a fresh install to setup basic settings and language
- [ ] Enable localization override in settings
- [ ] Re-translate extension into languages

Settings page TODO
- [x] Unlimited Quick Links control
- [x] Chrome Bookmarks Bar
- [ ] Clocks
- [ ] Date
- [ ] Search
- [ ] Custom message(s)
- [ ] Tab title options
- [ ] Global settings
- [ ] More font options (Full list of google fonts)
- [ ] Themes
- [ ] Layout options
- [ ] To Do list
- [ ] Notepad
- [ ] Background image
- [ ] Browser options (history, last closed tab, app page link, etc.)

Tab page TODO
- [ ] Quick Links
- [ ] Chrome Bookmarks Bar
- [ ] Clocks
- [ ] Date
- [ ] Search
- [ ] Custom message(s)
- [ ] To do list
- [ ] Notepad
- [ ] Browser options (history, last closed tab, app page link, etc.)

**Comment by hiergiltdiestfu** [comment]
Consider adding #80 please - thank you.

**Comment by bluecaret** [comment]
Update on CaretTab v3:

I apologize for the slowness in getting this update out. I have found myself with little to no time to finish this update recently. If anyone would like to contribute to get this finished any help and pull requests are appreciated! I did just release the 3rd beta today so progress is being made, but there is still a lot left to finish, the big one being localization which still needs a plugin to be setup to enable it.

You can sign up for the beta here: https://github.com/bluecaret/carettab/issues/104
